services:
  - type: web
    name: fintrace-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: corepack enable && pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://jgtarpigzpcadrsdmfhm.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: sb_publishable_bCRMFF6rrbHWCREJry4uMQ_rSAU4j0M
